<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Mandelbrot_Opdracht</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Mandelbrot Explorer</AssemblyName>
    <ApplicationIcon>Mandelbrot Explorer.ico</ApplicationIcon>
    <StartupObject>SmoothForm.Program</StartupObject>
    <Authors>Yuepeng He</Authors>
    <PackageIcon>view2.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Mandelbrot Explorer.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\previews\view2.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>